apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: carts-db
  labels:
    name: carts-db
  namespace: sock-shop
spec:
  serviceName: "carts-db"
  replicas: 3
  template:
    metadata:
      labels:
        name: carts-db
        role: mongo
        environment: sock-shop
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: carts-db
        image: mongo
        command:
          - mongod
          - "--replSet"
          - rs0
          - "--smallfiles"
          - "--noprealloc"        
        ports:
        - name: carts-db
          containerPort: 27017
        volumeMounts:
        - name: carts-db-pvc
          mountPath: /data/db
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "role=mongo,environment=sock-shop"        
  volumeClaimTemplates:
  - metadata:
      name: carts-db-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "cvo-single"
      resources:
        requests:
          storage: 100Gi